import Foundation
import UIKit


public class ContoDados {
    
    // Conto 1
    public static let conto1 = Conto(titulo: "Fotografia do Bem", descricao: "Uma história sobre crianças com necessidades especiais retratadas a mostrar diversas formas de ser feliz.", autor: "por  Mykaela Carbonera", fotos: [UIImage(named: "foto1")!, UIImage(named: "conto1-2.jpg")!, UIImage(named: "conto1-3.jpg")!, UIImage(named: "conto1-4.jpg")!, UIImage(named: "conto1-5.jpg")!], legendas: ["O projeto Fotografia do Bem começou em 2016 e hoje se tornou um movimento de cunho social e de combate ao preconceito. Começou com fotografias de animais de ONGs que precisavam de um novo lar. Em 2018, o projeto se estendeu à crianças com necessidades especiais, às vezes com a presença de animais resgatados.", "Quando comecei a fazer fotos de crianças, eu queria que tivesse uma causa social por trás de cada imagem. Por isso escolhi trabalhar com crianças especiais, inicialmente com autismo e síndrome de Down e depois as próprias mães foram indicando crianças com outras síndromes.", "O projeto, idealizado pela fotógrafa Mykaela Carbonera, que é gratuito para as famílias e ONGs, visa mostrar a beleza tanto das crianças quanto animais, através de imagens alegres. As fotos ressaltam o lado bom de cada criança e suas personalidades, além de conscientizar sobre as necessidades especiais das crianças.", "Nem todos conhecem as histórias sobre suas vidas e não conseguem enxergar além da condição em que a mesma se encontra. Por isso, o meu foco é mostrar alegria, brincadeiras com animais, em meio à natureza.", "Conforme avançam os trabalhos, eu aumento o meu portfólio, desenvolvo mais minha fotografia neste estilo fine art e divulgo o meu trabalho. Quanto às crianças e suas famílias, isto as ajuda a combater o preconceito, a divulgar informações e as presenteia com uma fotografia diferenciada, alegre e bonita daquela criança."])
    
    public static let conto2 = Conto(titulo: "O Poder dos Cachos", descricao: "Transição capilar como forma de empoderamento, aceitação e descoberta do seu novo eu.", autor: "por  Emily Silva", fotos: [UIImage(named: "Emily01.jpeg")!, UIImage(named: "Emily02.jpeg")!, UIImage(named: "Emily05.jpeg")!, UIImage(named: "Emily03.jpeg")!, UIImage(named: "Emily11.jpeg")!, UIImage(named: "Emily04.jpeg")!, UIImage(named: "Emily07.jpeg")!], legendas: ["2016 foi um ano de muita coisa nova. Passei no vestibular e iria começar na universidade só no segundo semestre. Até que então tentei fazer um nova mudança em mim, essa na qual se chama \"transição capilar\" e eu nem sabia o que significava.", "Ao ver o estado que estava meu cabelo e lembrar de como ele era durante minha infância e pré adolescência, me dei conta de que eu havia \"estragado\" meu cabelo com a química do alisamento. Lembrei de como ele era grande, saudável e tinha lindos cachos. Aí decidi me dar uma chance de mudar e tentar tê-lo de volta.", "Não foi fácil, mudanças não são. Fiquei 8 meses com um misto de raiz cacheada e pontas alisadas, usando óleos e receitas naturais pra acelerar o crescimento, mas também me desesperei e chorei pq muitas vezes eu não gostava de como ficava e pra sair de casa era um vexame.", "O medo de não ser aceita pelas outras pessoas me tomava e mal sabia eu que eu já tinha me aceitado e isso é o que basta! Quando se aproximou o início das aulas, eu me libertei.", "Cortei quase toda parte alisada, e ali vi um novo recomeço. Foi a reconstrução da minha autoestima.  E aqui 4 anos depois de todo esse processo, posso dizer que valeu muito a pena!", "Não é fácil, tive que lidar com olhares diferentes pro meu cabelo, com toda insegurança que eram depositadas em mim por outras pessoas. Mas com paciência hoje tenho o cabelo que tanto sonhei lá em 2016, que foi cuidado com todo carinho.", "Amar quem nós somos é o maior gesto que podemos fazer por nós mesmos. A transição é um período de muitas incerteza, mas que no fim vale muito a pena."])
    
    public static let conto3 = Conto(titulo: "Meu Primeiro Amor", descricao: "Gosta de amor, risadas e brincadeiras? Então não fique de fora dessa historia pois promete isso tudo e mais!", autor: "por Yasuo Sorye Ge Ton", fotos: [UIImage(named: "conto3.jpeg")!], legendas: ["calma que nao fiz ainda é so um teste bb"])
    
    public static let conto4 = Conto(titulo: "Religião & Expressão", descricao: "Promovendo igualdade e inclusão social dos povos de matriz africana.", autor: "por Rondinele", fotos: [UIImage(named: "conto4.png")!], legendas: ["calma que nao fiz ainda é so um teste bb"])
    
    public static let conto5 = Conto(titulo: "ONG Favela Mundo", descricao: "Economia colaborativa promovida por jovens com o objetivo de ofertar educação, formação e informação.", autor: "por Equipe Conexão", fotos: [UIImage(named: "conto5.png")!], legendas: ["calma que nao fiz ainda é so um teste bb"])
    
    
    public static var dadosGeral: [Conto] = [conto1, conto2, conto3, conto4, conto5]

    
    private init() {
        
    }
}
